### ISSUE TITLE
Message ID column too small?

### ISSUE THREAD

**Issue by kentdahl** [dmcbrn/laravel-email-database-log#5]
Anyone else started seeing message IDs from MailGun being too big?

```
SQLSTATE[22001]: String data, right truncated: 1406 
Data too long for column 'messageId' at row 1 
(SQL: insert into `my_prefix_email_log_events` 
(`messageId`, `event`, `timestamp_secs`, `timestamp_at`, `data`, `updated_at`, `created_at`) 
values (CAKK=Pq+3[LONG_51_CHAR_STRING_SNIPPED]Bmg, delivered, [....]
```

The size of the column was set to 32, but I do not know the rationale for that size.

* https://github.com/dmcbrn/laravel-email-database-log/blob/master/database/migrations/2018_07_05_131300_add_message_id_column.php
* https://github.com/dmcbrn/laravel-email-database-log/blob/master/database/migrations/2018_09_10_141916_create_email_log_events_table.php

Any hints or input before just upping it to an arbitrary larger size would be appreciated. 
So far not found anything in the MailGun docs on what size we can expect.

**Comment by dmcbrn** [comment]
I'm pretty busy at the moment so if you wanna do a pull request with a new migration changing it to 255 chars I'd gladly accept it.

I can't tell you for sure but since you can't find anything in MailGun docs I'd say I've set it to 32 based on glancing over the data I already had from MailGun.

If you want to be thorough please open a ticket with MailGun and let us know what they say.

Also, as a quick fix, I think it's safe to manually just up it in the database. Any future migration (changing it to size 255) should not give you any problems (99.99%). Not sure how mysql behaves so maybe just put it to 254 in case there's an error saying "it's already 255 long"

ps
Appreciate the feedback, it's nice to hear that library is being used.

**Comment by kentdahl** [comment]
Further digging shows that it appeared when I enabled one of the inbound routes in MailGun (while testing the mailing list functionality), so the longer IDs are caused by external mail systems. If you're only sending mails through MG, not receiving, then I think the limit is unlikely to be crossed, as far as I can tell.

I'll keep in mind to branch and pop you a PR once I get around to it myself. I think I have a few other things on my fork that might make sense for PRs after a little one-over and cleanup.

**Comment by kentdahl** [comment]
Closing this as I haven't seen it occur in any other cases.
